### ISSUE TITLE
Misspelling...?

### ISSUE THREAD

**Issue by 1MLightyears** [Adminbyaccident/FAMP#1]
At FAMP/stdard-famp.sh, line 28:

`tocuh /usr/local/etc/apache24/modules.d/001_mod-php.conf`

This "tocuh" seems a misspelling, do you mean:

`touch /usr/local/etc/apache24/modules.d/001_mod-php.conf`

?

**Comment by Adminbyaccident** [comment]
Changed. Thanks for the input.
